[gsheets]
type = "service_account"
project_id = "streamlit-nv"
private_key_id = "125fcd70913f8a958e352804e6b213d3e6ed3f8b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDoOxK2gxqQGhv1
0VjirsG81QN9r2wjJXX05lvHM3gi0nYBi6mKQLyME2kQe6unUXzUVUnph/N+mEQM
vUHUkdxuR8dPZE0PLHP4iWlmnqEetgZOhAp0WfsHB//3Yjvc+tIpSqbNSxMPMaEj
Lwqn/1CdVXYrmRWoNd8OOyX/7UB0HvYdSmCe8q9Vul8TRGRldJUVl5zC7XEsWsDM
01Btri7k4596sedWB9Yi0IkK+CiB+EzGtGn9Bz2Q5+pVDo4EJUA67z7dtQqjoVY/
q8lx6p/zkUK5gk4PkK/6hCUqEtcWFAQzteGbNP0nO9cEhse0VmasfH68Y0kCTSXA
x7vobcT3AgMBAAECggEAa0yUDlkQBmHR5me2WnJlWILRbJqHa8vMrv1ajXUV/nzg
gkFN8e+MTmpPgoqpmpLXiuHnVyv2ENl4o6w0ROup/hhTGjcdNbQT11NiLESB7Ect
LczraawDhNGo7lvojeckAGkaHcOgyEXljnSXR1z7md5ZTbabH4/YgmJI4fF0dNHR
47QxwKu9GTYJTLXunhy1AXrwX17eX1wXtdS6A65gx/59HDb3e59sstQqfy3d04mE
anlig0E6eUClKoyrWtRm5WQkwF8pN3m8RzhyVvwbHEP6rcJgp14JT0JXCaYA+JfT
qKiQXQgIGew+EcGHw9MqivoWtdndIjcgB+brn2wNvQKBgQD98PFwnpLsH/PKM9gf
yc8NIv7uxv/dtCdUq3AOcKoUU0Ts/PyXsGgXOe9xf1MibC40oyOYbF5gus37cgnL
w/jXuJD+GJFrGPHAFIweHya1T233zrcKODlcT9cLhAV5D++Y4v7fqnMvFsf4pj5d
L30pW7dPlwMDQfrb0HL7KU1t/QKBgQDqHRHfA4K8UxB/TK8kkfJhJ1BGLgSDw4ZN
qoIhQQ6ZoAlSYYm021BQpHw4nIu/6CrNorcya6C4H66i4qXitxOcIxiz3u4AS7Bu
DIwAfyAZ7mmIBLxJ+hdCPWuQdPH1HStR6zK6N7xji305LhWK0Mbw+wWD9bxMKK/6
JaLAf57XAwKBgQCDIFR789YoCYPIaKb0GzBIN0buo2Fh6PHaPcBaJIEeh7Tyrtv7
tAK745WpxLZ38uaVFZx+y46cYjmU2lkGmAY51jtAig0lATdsGPAVab6CJybArERG
CaxM54lCkASHc9wj1SsI8aoSqa/OzIEteyUlIw/wECllGD/iG6wT10r9PQKBgQCs
IM1388PWpRf3ELGhKLFVnysVPlZRbpu7VMcynfuXFiRkbpRp5enqMNWoZekWIyP9
Z0pchud3GMw0tIGU7Fg9r0xFS34ft4azkwQIhW9bwX/T4u9xULBzImeIoYMYXebw
5wW4Bqy7X96lAO4TzybGHTnT6QQV1sB0IeHEuNBXcwJ/WiBj8ZZyQAke32BUSWx5
9W2H1YWMXJjfmbX7wCfv1xQwQbV9NCeVNreZ+wqatZXeFTn7g4mCVSWikBEzXLyn
J9pWgTerxSlfGukJyWFmbWyqUl8BAL+P+0FPMHOWw/YjjOT/tYuYN9tI4u2AIwS7
JGIXaST3ZxZz7Oicx9N2gA==
-----END PRIVATE KEY-----"""
client_email = "streamlit-bot@streamlit-nv.iam.gserviceaccount.com"
client_id = "111435003909414977009"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-bot@streamlit-nv.iam.gserviceaccount.com"
